# Generated by Django 5.1.4 on 2024-12-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='business_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
