# Generated by Django 4.1.7 on 2023-03-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Super Admin'), (2, 'Admin'), (3, 'Mentor'), (4, 'Student'), (5, 'Business')], default=4),
        ),
    ]
