# Generated by Django 5.1.4 on 2024-12-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_business_remove_myuser_business_name_myuser_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
