# Generated by Django 4.1.7 on 2023-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
