# Generated by Django 4.2.1 on 2023-05-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_new_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'managed': True, 'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
    ]
