# Generated by Django 4.2.1 on 2023-05-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_myuser_options_myuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='time_zone',
            field=models.CharField(default='America/Vancouver'),
        ),
    ]
