# Generated by Django 4.2.1 on 2023-06-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_myuser_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='other_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
