# Generated by Django 4.2.1 on 2023-08-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_myuser_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
