# Generated by Django 4.2.1 on 2023-09-22 01:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_myuser_status_alter_myuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=['contentOryx7'], max_length=30, null=True, unique=True, validators=[accounts.models.validate_username]),
        ),
    ]
