# Generated by Django 4.2.1 on 2024-07-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_category_description_category_image'),
        ('accounts', '0011_alter_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='skills',
            field=models.ManyToManyField(to='courses.tag'),
        ),
    ]
