# Generated by Django 5.1.4 on 2024-12-06 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('pet', 'Pet'), ('brand_ambassador', 'Brand Ambassador'), ('employee', 'Employee'), ('authorized_dealer', 'Authorized Dealer'), ('authorized_retailer', 'Authorized Retailer'), ('authorized_reseller', 'Authorized Reseller'), ('authorized_service_provider', 'Authorized Service Provider'), ('authorized_installer', 'Authorized Installer'), ('certification_organization', 'Certification Organization'), ('third_party_certifier', 'Third Party Certifier')], default='personal', max_length=50)),
                ('update_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_in_bios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link In Bio',
                'verbose_name_plural': 'Link In Bios',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_in_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='home.linkinbio')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
