# Generated by Django 5.1.4 on 2024-12-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_link_description_link_image_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
