# Generated by Django 5.1.4 on 2024-12-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_link_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkinbio',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
