# Generated by Django 5.1.4 on 2024-12-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_linkinbio_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
